### ISSUE TITLE
wrong media query order

### ISSUE THREAD

**Issue by iapYang** [MadLittleMods/postcss-css-variables#53] opened 2017-07-13 09:22 UTC
Thanks for your work.
Recently I've been using this plugin, It worked well but some error occurs.

Here is my original code:
```
:root {
	--color: green; 
}

div {
	color: var(--color);
}

@meida (max-width: 10000px) {
	:root {
		--color: red;
	}
}

@meida (max-width: 1000px) {
	:root {
		--color: yellow;
	}
}
```

and I used playground output is:
```
div {
	color: green;
}

@meida (max-width: 1000px) {

	div {
		color: yellow;
	}
}

@meida (max-width: 10000px) {

	div {
		color: red;
	}
}
```

The media query order is a in a wrong one, is that something can be fixed?

Thanks!~

**Comment by MadLittleMods** [comment] 2017-07-13 14:34
Duplicate of https://github.com/MadLittleMods/postcss-css-variables/issues/30

**Closed by MadLittleMods** 2017-07-13 14:34 UTC
