### ISSUE TITLE
Do not duplicate blocks of multiple comma separated selectors

### ISSUE THREAD

**Issue by SuperPat45** [MadLittleMods/postcss-css-variables#110] opened 2019-10-23 14:27 UTC
Input:

```css
:root {
  --font-size: 12px;
  --font-family: roboto, "Helvetica Neue", Helvetica, Arial, sans-serif;
}
html,body {
  font-family: var(--font-family);
  font-size: var(--font-size);
}
```

Actual output:
```css
:root {
  --font-size: 12px;
  --font-family: roboto, "Helvetica Neue", Helvetica, Arial, sans-serif;
}
html {
  font-family: roboto, "Helvetica Neue", Helvetica, Arial, sans-serif;
  font-family: var(--font-family);
  font-size: 12px;
  font-size: var(--font-size);
}
body {
  font-family: roboto, "Helvetica Neue", Helvetica, Arial, sans-serif;
  font-family: var(--font-family);
  font-size: 12px;
  font-size: var(--font-size);
}
```

Expected:
```css
:root {
  --font-size: 12px;
  --font-family: roboto, "Helvetica Neue", Helvetica, Arial, sans-serif;
}
html,body {
  font-family: roboto, "Helvetica Neue", Helvetica, Arial, sans-serif;
  font-family: var(--font-family);
  font-size: 12px;
  font-size: var(--font-size);
}
```

**Comment by MadLittleMods** [comment] 2019-11-25 01:44
Duplicate of https://github.com/MadLittleMods/postcss-css-variables/issues/58

Related to https://github.com/MadLittleMods/postcss-css-variables/issues/67, https://github.com/MadLittleMods/postcss-css-variables/issues/105

**Closed by MadLittleMods** 2019-11-25 01:44 UTC
Labels: bug
